# Generated by Django 5.2.1 on 2025-07-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.class')),
                ('subjects', models.ManyToManyField(blank=True, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Class Teaching Assignment',
                'verbose_name_plural': 'Class Teaching Assignments',
                'unique_together': {('classroom', 'teacher')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='classes', through='academics.ClassTeaching', through_fields=('classroom', 'teacher'), to='teachers.teacher'),
        ),
    ]
