# Generated by Django 5.2.1 on 2025-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_options_alter_subject_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.CharField(default=2025, max_length=20),
            preserve_default=False,
        ),
    ]
