# Generated by Django 5.2.1 on 2025-09-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_file',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
