# Generated by Django 5.2.1 on 2025-09-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('teachers', '0002_alter_teacher_options_teacher_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
    ]
